[project]
name = "ocp-web"
version = "0.1.0"
description = "OCP Web Viewer with drag & drop build123d support"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask",
    "flask-cors",
    "orjson",
    "build123d",
    "ocp-tessellate"
]
